version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    volumes:
      - ./auth-service:/app
    networks:
      - bookstore-net

  book-service:
    build: ./book-service
    ports:
      - "5001:5001"
    volumes:
      - ./book-service:/app
    networks:
      - bookstore-net

  orders-service:
    build: ./orders-service
    ports:
      - "5003:5003"
    volumes:
      - ./orders-service:/app
    networks:
      - bookstore-net
  api-gateway:
    build: ./api-gateway
    ports:
      - "5002:5002"
    volumes:
      - ./api-gateway:/app
    networks:
      - bookstore-net
    depends_on:
      - auth-service
      - book-service
      - orders-service
      
  

networks:
  bookstore-net:
    driver: bridge
